### ISSUE TITLE
cbgen "Could not open file"

### ISSUE THREAD

**Issue by dllaboss** [byt3smith/Forager#7]
What is the solution to this problem?

Thanks

![forager error](https://cloud.githubusercontent.com/assets/18423888/14465609/97804c30-00a1-11e6-9a34-6e00e3720da3.PNG)

**Comment by burdenless** [comment]
Looks like a bug from the directory structure refactoring, I will push out a bugfix today. Thanks for reporting this 👍

**Comment by dllaboss** [comment]
Fantastic! Thanks for the prompt response!

**Comment by burdenless** [comment]
Resolved in #8
